services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQLDB_HOST=$MYSQLDB_HOST
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db_hola_mundo_ia:/var/lib/mysql
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    env_file: ./.env
    environment:
      - NGROK_AUTHTOKEN=$NGROK_AUTHTOKEN
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/myapp
    command: sh -c "npm install && npm run dev"

volumes:
  db_hola_mundo_ia:
